### PR TITLE
Fixed author reviewing its own PR

### LINKED ISSUE #5: Limit author's permissions to change status
Authors of a PR/issue should be prevented to change the status of their PR/issue to anything else but "Needs Review". So they cannot do:
- "Needs Review" -> "Reviewed"

However, they can do:
- "Needs Work" -> "Needs Review"

### PR DESCRIPTION
**Pull request by HeahDude**
Closes #5.

### CODE REVIEW

File: src/AppBundle/Subscriber/StatusChangeByCommentSubscriber.php [hunk 1]
```diff
@@ -50,6 +50,15 @@ public function onIssueComment(GitHubEvent $event)
             // Second subpattern = first status character
             $newStatus = static::$triggerWordToStatus[strtolower(end($matches[1]))];
 
+            if (Status::REVIEWED === $newStatus && false === $this->checkUserIsAllowedToReview($data)) {
```
Comment (xabbuh) [inline src/AppBundle/Subscriber/StatusChangeByCommentSubscriber.php]: `!$this->checkUserIsAllowedToReview($data)`

**Comment by weaverryan** [comment]
And thank you again! :)
